### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'str' and 'int'

### ISSUE THREAD

**Issue by pimbolilu** [cipavlou/linkedin-viewer-bot#1]
Hello,

I get this error:

Enter how many LinkedIn profiles you wish to view95
Traceback (most recent call last):
  File "C:\Users\User\Documents\linkedin_viewer_bot.py", line 25, in <module>
    page_max = round(no_of_profiles/10) + i
TypeError: unsupported operand type(s) for /: 'str' and 'int'

Can you tell me whats the problem about?

br

**Comment by cipavlou** [comment]
What version of Python are you using?

So that error is caused by one of either "i" or "round(no_of_profiles/10)" being a string. I've just rerun the code myself and no issues but if you change to:

page_max = int(round(no_of_profiles/10)) + int(i) it should solve it

**Comment by pimbolilu** [comment]
thanks for the fast reply.

I changed the line but without success:
$Enter how many LinkedIn profiles you wish to view10
Traceback (most recent call last):
  File "C:\Users\User\Documents\linkedin_viewer_bot.py", line 25, in <module>
    page_max = int(round(no_of_profiles/10))
TypeError: unsupported operand type(s) for /: 'str' and 'int'

I use python 3.5 on windows

**Comment by cipavlou** [comment]
Line 12 should be: no_of_profiles = int(input("Enter how many LinkedIn profiles you wish to view")) - my local copy is different to the one on Git, will try and push now

**Comment by pimbolilu** [comment]
perfect works!

thanks for your help
